---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: compress /tmp
      archive:
        path: /tmp
        dest: tmp.tgz

    - name: check network facts
      assert:
        that:
          - ansible_default_ipv4.broadcast is defined
